# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InicialH20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InicialNO3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCultivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='fechasiembra',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='inicialesH20',
            field=models.ManyToManyField(to='webapp.InicialH20'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='inicialesNO3',
            field=models.ManyToManyField(to='webapp.InicialNO3'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='suelos',
            field=models.ManyToManyField(to='webapp.Suelo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipocultivares',
            field=models.ManyToManyField(to='webapp.TipoCultivar'),
        ),
    ]
