# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20160630_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicialh20',
            old_name='suelo',
            new_name='cultivos',
        ),
        migrations.AddField(
            model_name='inicialno3',
            name='cultivos',
            field=models.ManyToManyField(to='webapp.Cultivo'),
        ),
    ]
