# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20160630_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicialh20',
            name='cultivos',
        ),
        migrations.RemoveField(
            model_name='inicialno3',
            name='cultivos',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='h2os',
            field=models.ManyToManyField(to='webapp.InicialH20'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='no3s',
            field=models.ManyToManyField(to='webapp.InicialNO3'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='suelos',
            field=models.ManyToManyField(to='webapp.Suelo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo_cultivares',
            field=models.ManyToManyField(to='webapp.TipoCultivar'),
        ),
    ]
