# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20160701_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionmeteorologica',
            name='etiqueta',
            field=models.CharField(default='qwe', max_length=100),
            preserve_default=False,
        ),
    ]
