# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_estacionmeteorologica_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='suelo',
            name='etiqueta',
            field=models.CharField(default=datetime.datetime(2016, 7, 6, 12, 59, 14, 242000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
