# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_tipofertilizante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AplicacionFertilizante',
        ),
        migrations.DeleteModel(
            name='TipoFertilizante',
        ),
    ]
