# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_fertilizante'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
