# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_aplicacionf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocultivar',
            name='etiqueta',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
