# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_tipocultivar_etiqueta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocultivar',
            old_name='etiqueta',
            new_name='valor',
        ),
    ]
