# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20160711_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionmeteorologica',
            name='valor',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
