# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_estacionmeteorologica_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='suelo',
            name='valor',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
