# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_inicialno3_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionf',
            name='valor',
            field=models.CharField(default='g', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='valor',
            field=models.CharField(default='g', max_length=100),
            preserve_default=False,
        ),
    ]
