# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20160711_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicialh20',
            name='valor',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
