# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_inicialh20_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='riego',
            name='valor',
            field=models.CharField(default='a2', max_length=100),
            preserve_default=False,
        ),
    ]
