# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_riego_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.IntegerField()),
                ('procesamiento', models.IntegerField()),
            ],
        ),
    ]
