# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_administrativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionf',
            name='etiqueta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='etiqueta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inicialh20',
            name='etiqueta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inicialno3',
            name='etiqueta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riego',
            name='etiqueta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocultivar',
            name='etiqueta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
