# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-16 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_tipo_suelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_suelo',
        ),
    ]
