# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-16 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_tipo_suelo_f1_tipo_suelo_f2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_suelo_f2',
            name='valor',
        ),
    ]
