# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-16 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_remove_tipo_suelo_f2_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_suelo_f1',
            name='valor',
        ),
    ]
