# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-16 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_remove_tipo_suelo_f1_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_suelo_f1',
            name='etiqueta',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tipo_suelo_f1',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
    ]
